version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_VERSION: 16.1
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  server:
    container_name: lost_and_found_server
    restart: unless-stopped
    image: lost-and-found-server-dev:tag-v1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - postgres

  client:
    container_name: lost_and_found_client
    restart: unless-stopped
    image: lost-and-found-client-dev:tag-v1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network:
