name: Docker Image CI for Github Container Registry

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_DATABASE: ${{ secrets.PG_DATABASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

      - name: Build and push Docker image
        run: |
          # Build and push PostgreSQL service image
          docker-compose -f docker-compose.yml build postgres
          docker-compose -f docker-compose.yml push postgres

          # Build and push Server service image
          docker-compose -f docker-compose.yml build server
          docker-compose -f docker-compose.yml push server

          # Build and push Client service image
          docker-compose -f docker-compose.yml build client
          docker-compose -f docker-compose.yml push client
