name: Docker Image CI for Github Container Registry

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login --username ${{ github.repository_owner }} --password-stdin ghcr.io

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build --parallel --compress --quiet --tag ghcr.io/${{ github.repository }}-ghcr:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-ghcr:latest
